# Generated by Django 6.1.1 on 2026-09-16 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Carrera')),
                ('race_type', models.CharField(choices=[('TRAIL', 'Trail Running'), ('STREET', 'Carrera de Calle'), ('TRIATHLON', 'Triatlón'), ('MTB', 'Mountain Bike')], max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Fecha del Evento')),
                ('training_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Inicio del Entrenamiento')),
                ('target_distance_km', models.FloatField(verbose_name='Distancia (km)')),
                ('target_elevation_gain', models.IntegerField(default=0, verbose_name='Desnivel Positivo (+m)')),
                ('target_pace', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo/Tiempo Objetivo')),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx_tracks/', verbose_name='Archivo GPX')),
                ('is_completed', models.BooleanField(default=False, verbose_name='¿Completada?')),
            ],
        ),
    ]
