# Generated by Django 6.1.1 on 2026-09-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racegoal',
            name='bike_distance_km',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ciclismo (km)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='bike_speed',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Velocidad Bici (km/h)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='run_distance_km',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Running (km)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='run_pace',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo Run (min/km)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='swim_distance_m',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Natación (m)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='swim_pace',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo Nado (min/100m)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='t1_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiempo T1 (Transición 1)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='t2_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiempo T2 (Transición 2)'),
        ),
        migrations.AlterField(
            model_name='racegoal',
            name='target_distance_km',
            field=models.FloatField(verbose_name='Distancia Total (km)'),
        ),
    ]
