# Generated by Django 6.1.1 on 2026-09-17 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_racegoal_bike_distance_km_racegoal_bike_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racegoal',
            name='expected_te',
            field=models.FloatField(blank=True, null=True, verbose_name='Training Effect Esperado (1.0 - 5.0)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='nutrition_strategy',
            field=models.TextField(blank=True, help_text='Ej: Gel cada 45min, 500ml isotónica por hora.', null=True, verbose_name='Estrategia de Nutrición e Hidratación'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='target_hr_zone',
            field=models.CharField(blank=True, choices=[('Z1', 'Zona 1 (Regenerativo)'), ('Z2', 'Zona 2 (Fondo Aeróbico)'), ('Z3', 'Zona 3 (Tempo)'), ('Z4', 'Zona 4 (Umbral)'), ('Z5', 'Zona 5 (Máximo)')], max_length=5, null=True, verbose_name='Zona FC Objetivo'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatura Estimada (°C)'),
        ),
        migrations.AddField(
            model_name='racegoal',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('SUNNY', '☀️ Despejado / Soleado'), ('CLOUDY', '☁️ Nublado'), ('RAIN', '🌧️ Lluvia'), ('SNOW', '❄️ Nieve / Frío extremo')], max_length=20, null=True, verbose_name='Clima Esperado'),
        ),
        migrations.AlterField(
            model_name='racegoal',
            name='t1_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiempo T1'),
        ),
        migrations.AlterField(
            model_name='racegoal',
            name='t2_time',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiempo T2'),
        ),
        migrations.CreateModel(
            name='RaceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del PAS / Control')),
                ('km_mark', models.FloatField(verbose_name='Kilómetro')),
                ('cut_off_time', models.TimeField(blank=True, null=True, verbose_name='Tiempo de Corte')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='goals.racegoal')),
            ],
            options={
                'ordering': ['km_mark'],
            },
        ),
    ]
