# Generated by Django 6.1.1 on 2026-09-16 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Repuesto')),
                ('installed_date', models.DateField(verbose_name='Fecha de Instalación')),
                ('max_lifespan_km', models.FloatField(verbose_name='Vida Útil Estimada (km)')),
                ('current_mileage', models.FloatField(default=0.0, verbose_name='Kilometraje Actual')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está en uso?')),
            ],
        ),
        migrations.CreateModel(
            name='CyclingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration', models.DurationField(default=datetime.timedelta, verbose_name='Tiempo Total')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC Promedio (LPM)')),
                ('te_aerobic', models.FloatField(blank=True, null=True, verbose_name='TE Aeróbico (0-5)')),
                ('te_anaerobic', models.FloatField(blank=True, null=True, verbose_name='TE Anaeróbico (0-5)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas / Nutrición / Mecánica')),
                ('distance_km', models.FloatField(verbose_name='Distancia (km)')),
                ('elevation_gain', models.IntegerField(default=0, verbose_name='Desnivel Positivo (+m)')),
                ('avg_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad Promedio (km/h)')),
                ('avg_cadence', models.IntegerField(blank=True, null=True, verbose_name='Cadencia Promedio (ppm)')),
                ('avg_power', models.IntegerField(blank=True, null=True, verbose_name='Potencia Promedio (Watts)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration', models.DurationField(default=datetime.timedelta, verbose_name='Tiempo Total')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC Promedio (LPM)')),
                ('te_aerobic', models.FloatField(blank=True, null=True, verbose_name='TE Aeróbico (0-5)')),
                ('te_anaerobic', models.FloatField(blank=True, null=True, verbose_name='TE Anaeróbico (0-5)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas / Nutrición / Mecánica')),
                ('is_trail', models.BooleanField(default=False, verbose_name='¿Es Trail?')),
                ('distance_km', models.FloatField(verbose_name='Distancia (km)')),
                ('elevation_gain', models.IntegerField(default=0, verbose_name='Desnivel Positivo (+m)')),
                ('avg_pace', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo Promedio (min/km)')),
                ('cadence', models.IntegerField(blank=True, null=True, verbose_name='Cadencia (ppm)')),
                ('stride_length', models.FloatField(blank=True, null=True, verbose_name='Longitud de Zancada (m)')),
                ('vertical_oscillation', models.FloatField(blank=True, null=True, verbose_name='Oscilación Vertical (cm)')),
                ('ground_contact_time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Contacto (ms)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwimActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duration', models.DurationField(default=datetime.timedelta, verbose_name='Tiempo Total')),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC Promedio (LPM)')),
                ('te_aerobic', models.FloatField(blank=True, null=True, verbose_name='TE Aeróbico (0-5)')),
                ('te_anaerobic', models.FloatField(blank=True, null=True, verbose_name='TE Anaeróbico (0-5)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas / Nutrición / Mecánica')),
                ('is_open_water', models.BooleanField(default=False, verbose_name='¿Aguas Abiertas?')),
                ('distance_meters', models.IntegerField(verbose_name='Distancia (metros)')),
                ('strokes', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Brazadas')),
                ('swolf', models.IntegerField(blank=True, null=True, verbose_name='SWOLF')),
                ('avg_pace_100m', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ritmo (min/100m)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
