# Generated by Django 6.1.1 on 2026-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Peso Diario (kg)')),
                ('resting_heart_rate', models.IntegerField(blank=True, null=True, verbose_name='FC Reposo (LPM)')),
                ('sleep_score', models.IntegerField(blank=True, null=True, verbose_name='Puntuación de Sueño (0-100)')),
                ('stress_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Estrés (0-100)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas (Ej: dolor de garganta, cansancio extremo)')),
            ],
        ),
        migrations.CreateModel(
            name='ErgometryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha del Estudio')),
                ('doctor_or_clinic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Doctor / Institución')),
                ('weight_kg', models.FloatField(verbose_name='Peso (kg)')),
                ('height_cm', models.FloatField(default=173, verbose_name='Altura (cm)')),
                ('z1_min', models.IntegerField(default=127, verbose_name='Z1 Min (Regenerativo)')),
                ('z1_max', models.IntegerField(default=141, verbose_name='Z1 Max')),
                ('z2_min', models.IntegerField(default=142, verbose_name='Z2 Min (Aeróbico)')),
                ('z2_max', models.IntegerField(default=154, verbose_name='Z2 Max')),
                ('z3_min', models.IntegerField(default=155, verbose_name='Z3 Min (Umbral)')),
                ('z3_max', models.IntegerField(default=169, verbose_name='Z3 Max')),
                ('z4_min', models.IntegerField(default=170, verbose_name='Z4 Min (Anaeróbico)')),
                ('z4_max', models.IntegerField(default=182, verbose_name='Z4 Max')),
                ('z5_min', models.IntegerField(default=183, verbose_name='Z5 Min (Máximo)')),
                ('z5_max', models.IntegerField(default=198, verbose_name='Z5 Max')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Conclusiones / Notas del Médico')),
            ],
        ),
    ]
